version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest 
    steps:
      - run: |
          apt update
          apt install -y hdf5-tools libhdf5-serial-dev libbz2-dev liblzma-dev libcurl4-openssl-dev python3-dev python2-dev python3-pip
          pip install --upgrade pip
      - checkout
      - run: |
          pip install . --ignore-installed six
          bash .circleci/run_test.sh
